package xfinitywifi

// This code was generated by Gemini.  Let's rework it into a plugin.
// The plugin should provide a status page that shows info on the current status, and the last probe attempt.

import (
	"context"
	"crypto/tls"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/http/cookiejar"
	"net/url"
	"strings"
	"time"
)

const (
	// How often to check the connection
	checkInterval = 30 * time.Second

	// Comcast Credentials
	xfinityUser = "YOUR_XFINITY_USERNAME_OR_EMAIL"
	xfinityPass = "YOUR_XFINITY_PASSWORD"
)

// List of reliable endpoints used by major OSes to detect captive portals
var probeTargets = []string{
	"http://connectivitycheck.gstatic.com/generate_204", // Returns 204
	"http://detectportal.firefox.com/success.txt",       // Returns 200 "success\n"
	"http://www.apple.com/library/test/success.html",    // Returns 200 with small HTML
}

func main() {
	log.Println("🚀 Starting Xfinity Host-Side Keep-Alive Daemon...")

	ticker := time.NewTicker(checkInterval)
	defer ticker.Stop()

	// Run an immediate check on startup
	if !checkConnectivity() {
		handleReauth()
	}

	for range ticker.C {
		if !checkConnectivity() {
			handleReauth()
		}
	}
}

// checkConnectivity probes multiple targets. Returns true if we have open internet.
func checkConnectivity() bool {
	// Create a client that DOES NOT follow redirects so we can detect captive portals
	client := &http.Client{
		Timeout: 5 * time.Second,
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}

	successes := 0

	for _, target := range probeTargets {
		ctx, cancel := context.WithTimeout(context.Background(), 4*time.Second)
		req, err := http.NewRequestWithContext(ctx, "GET", target, nil)
		if err != nil {
			cancel()
			continue
		}

		resp, err := client.Do(req)
		cancel()
		if err != nil {
			// Network error (no IP, DNS resolution failed, etc.)
			continue
		}
		resp.Body.Close()

		// Captive portals hijack requests with a 302/307 redirect,
		// or rewrite the body with a 200 OK containing their login page.
		if resp.StatusCode >= 300 && resp.StatusCode < 400 {
			log.Printf("⚠️ Target %s redirected. Captive portal detected.\n", target)
			return false
		}

		if resp.StatusCode == http.StatusNoContent || resp.StatusCode == http.StatusOK {
			successes++
		}
	}

	// If at least two targets succeed, we consider the connection healthy
	return successes >= 2
}

// handleReauth coordinates the multi-step Comcast login sequence
func handleReauth() {
	log.Println("📡 Connection down or hijacked. Attempting Comcast authentication...")

	// Create a cookie jar to persist session cookies across the auth flow
	jar, err := cookiejar.New(nil)
	if err != nil {
		log.Printf("❌ Failed to create cookie jar: %v\n", err)
		return
	}

	client := &http.Client{
		Timeout: 20 * time.Second,
		Jar:     jar,
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
	}

	// Step 1: Hit a non-SSL target to force the captive portal intercept redirect
	log.Println("[Step 1] Triggering redirect intercept...")
	resp, err := client.Get("http://neverssl.com")
	if err != nil {
		log.Printf("❌ Failed to hit trigger URL: %v\n", err)
		return
	}
	defer resp.Body.Close()

	bodyBytes, _ := io.ReadAll(resp.Body)
	bodyStr := string(bodyBytes)

	// Step 2: Parse necessary hidden tokens from the landing page.
	// Comcast portal flows typically rely on state/token variables
	// (like 'execution', 'xsrf', or session IDs) embedded in the HTML.
	log.Println("[Step 2] Parsing login state parameters...")

	actionURL, payload, err := parseXfinityLoginPage(bodyStr)
	if err != nil {
		log.Printf("❌ Failed to parse login page elements: %v\n", err)
		// Fallback: log the HTML output to help debug structural changes
		log.Printf("HTML Snippet: %.500s...\n", bodyStr)
		return
	}

	// Add the actual credentials to the parsed payload
	payload.Set("username", xfinityUser)
	payload.Set("password", xfinityPass)

	// Step 3: POST the authentication payload back to the portal
	log.Println("[Step 3] Submitting Comcast credentials...")
	req, err := http.NewRequest("POST", actionURL, strings.NewReader(payload.Encode()))
	if err != nil {
		log.Printf("❌ Failed to create login request: %v\n", err)
		return
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	authResp, err := client.Do(req)
	if err != nil {
		log.Printf("❌ Authentication post failed: %v\n", err)
		return
	}
	defer authResp.Body.Close()

	// Step 4: Verify connection recovery
	time.Sleep(3 * time.Second) // Let DHCP/routing settle if necessary
	if checkConnectivity() {
		log.Println("✅ Portal login successful! Internet access restored.")
	} else {
		log.Println("❌ Auth submitted, but keep-alive checks are still failing.")
	}
}

// parseXfinityLoginPage extracts target form action and hidden fields from the portal.
func parseXfinityLoginPage(html string) (string, url.Values, error) {
	payload := url.Values{}

	// --- COMPONENT REAL-WORLD IMPLEMENTATION NOTE ---
	// You will need to inspect the Comcast page HTML source code to match their selectors.
	// Typically, you can find fields like:
	// <input type="hidden" name="execution" value="e1s1" />
	// <form action="https://login.xfinity.com/login" method="post">
	//
	// For simplicity and dependency reduction, we use standard string searching here,
	// but using "golang.org/x/net/html" to parse the DOM is highly recommended.

	var actionURL string
	if strings.Contains(html, "action=\"") {
		// Scrape the form destination
		parts := strings.Split(html, "action=\"")
		if len(parts) > 1 {
			actionURL = strings.Split(parts[1], "\"")[0]
		}
	} else {
		// Fallback to standard Comcast entry point if parser misses it
		actionURL = "https://login.xfinity.com/login"
	}

	// Example parsing of standard Spring Security 'execution' tokens:
	if strings.Contains(html, "name=\"execution\"") {
		parts := strings.Split(html, "name=\"execution\"")
		if len(parts) > 1 {
			valParts := strings.Split(parts[1], "value=\"")
			if len(valParts) > 1 {
				executionVal := strings.Split(valParts[1], "\"")[0]
				payload.Set("execution", executionVal)
			}
		}
	}

	// Always require a valid target action URL
	if actionURL == "" {
		return "", nil, fmt.Errorf("could not isolate form action URL")
	}

	return actionURL, payload, nil
}
